/*
/////////////////////////////////////////////////////

/////////////////////////////////////////////////////

*/

//Turn Eigen bounds checking off for speed.
#ifndef EIGEN_NO_DEBUG
#define EIGEN_NO_DEBUG
#endif

#include <vector>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <omp.h>
#include <iostream>


#include "calc_deformation_forces.hpp"
#include "Tri_Class.hpp"
#include "Stuff_Class.hpp"
#include "Out_Stream_Class.hpp"

void calc_deformation_forces(
    Eigen::Matrix<double,Eigen::Dynamic,1> &forces,
    Eigen::Matrix<double,Eigen::Dynamic,1> &del_energy_by_del_continuum_quantities,
    const Eigen::Matrix<double,Eigen::Dynamic,1> &continuum_quantities,
    const Eigen::Matrix<double,Eigen::Dynamic,1> &def_shear_moduli,
    const Eigen::Matrix<double,Eigen::Dynamic,1> &def_thicknesses,
    const Eigen::Matrix<double,Eigen::Dynamic,3> &abar_comps,
    const Eigen::Matrix<double,Eigen::Dynamic,3> &bbar_comps,
    const Eigen::SparseMatrix<double, Eigen::RowMajor> &mat_for_continuum_quantities_from_dofs_transpose,
    const std::vector<Tri_Class> &triangles,
    const Stuff_Class &stuff,
    [[maybe_unused]] Out_Stream_Class &log){

    #pragma omp parallel for simd
    for(int t = 0; t < stuff.num_tris; ++t){

        // Index into continuum_quantities that is the start of triangle t's set of 15 continuum quantities
        int q = 15*t;

        // continuum_quantities structure will be 
        // (tri1_Xx, tri1_Xy, tri1_Xxx, tri1_Xxy, tri1_Xyy, tri1_Yx, tri1_Yy, tri1_Yxx, tri1_Yxy, tri1_Yyy, tri1_Zx, tri1_Zy, tri1_Zxx, tri1_Zxy, tri1_Zyy, tri2_Xx, ...)
        //     0        1         2        3          4       5         6        7         8         9        10       11        12       13         14
        double Xx  = continuum_quantities(q+0);
        double Xy  = continuum_quantities(q+1);
        double Xxx = continuum_quantities(q+2);
        double Xxy = continuum_quantities(q+3);
        double Xyy = continuum_quantities(q+4);
        double Yx  = continuum_quantities(q+5);
        double Yy  = continuum_quantities(q+6);
        double Yxx = continuum_quantities(q+7);
        double Yxy = continuum_quantities(q+8);
        double Yyy = continuum_quantities(q+9);
        double Zx  = continuum_quantities(q+10);
        double Zy  = continuum_quantities(q+11);
        double Zxx = continuum_quantities(q+12);
        double Zxy = continuum_quantities(q+13);
        double Zyy = continuum_quantities(q+14);

        double char_bend_energy_density_for_one_over_thickness_curv = def_shear_moduli(t) * def_thicknesses(t);
        double bend_stiffening_energy_density_scale = stuff.bend_stiffening_scale_factor * char_bend_energy_density_for_one_over_thickness_curv;

        double abar0 = abar_comps(t,0);
        double abar1 = abar_comps(t,1);
        double abar2 = abar_comps(t,2);
        double bbar0 = bbar_comps(t,0);
        double bbar1 = bbar_comps(t,1);
        double bbar2 = bbar_comps(t,2);

        ///////////////////////////////////////////////////////////////////////////////////////
        // Copy-paste the contents of energy1stDerivsCpp.txt (generated by Mathematica) between 
        // this comment and the double row of slashes at the end of the for loop.

                
        double stretch_prefac = (-2*def_thicknesses(t)*def_shear_moduli(t)*(1/(-(abar1*abar1) + abar0*abar2))*(1/sqrt(-(abar1*abar1) + abar0*abar2)))/(-1 + stuff.def_poisson_ratio); 

        double bend_prefac = (def_shear_moduli(t)*(1/(-(abar1*abar1) + abar0*abar2))*(def_thicknesses(t)*def_thicknesses(t)*def_thicknesses(t))*(1/sqrt(-(abar1*abar1) + abar0*abar2)))/(6 - 6*stuff.def_poisson_ratio); 

        double n0 = (-(Yy*Zx) + Yx*Zy)*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double n1 = (Xy*Zx - Xx*Zy)*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double n2 = (-(Xy*Yx) + Xx*Yy)*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn0dXx = (Yy*Zx - Yx*Zy)*(-(Xy*(Yx*Yy + Zx*Zy)) + Xx*((Yy*Yy) + (Zy*Zy)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn0dYx = (Xy*Zx - Xx*Zy)*(Xy*(Yx*Yy + Zx*Zy) - Xx*((Yy*Yy) + (Zy*Zy)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn0dZx = -((Xy*Yx - Xx*Yy)*(Xy*(Yx*Yy + Zx*Zy) - Xx*((Yy*Yy) + (Zy*Zy)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn0dXy = -((Yy*Zx - Yx*Zy)*(Xx*(Yx*Yy + Zx*Zy) - Xy*((Yx*Yx) + (Zx*Zx)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn0dYy = -((Xy*Zx - Xx*Zy)*(-(Xx*(Yx*Yy + Zx*Zy)) + Xy*((Yx*Yx) + (Zx*Zx)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn0dZy = (Xy*Yx - Xx*Yy)*(-(Xx*(Yx*Yy + Zx*Zy)) + Xy*((Yx*Yx) + (Zx*Zx)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn1dXx = -((Yy*Zx - Yx*Zy)*(Xx*Xy*Yy + Zy*(Yy*Zx - Yx*Zy) - Yx*(Xy*Xy))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn1dYx = -((Xy*Zx - Xx*Zy)*(-(Xx*Xy*Yy) + Zy*(-(Yy*Zx) + Yx*Zy) + Yx*(Xy*Xy))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn1dZx = (Xy*Yx - Xx*Yy)*(-(Xx*Xy*Yy) + Zy*(-(Yy*Zx) + Yx*Zy) + Yx*(Xy*Xy))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn1dXy = (Yy*Zx - Yx*Zy)*(-(Xx*Xy*Yx) + Zx*(Yy*Zx - Yx*Zy) + Yy*(Xx*Xx))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn1dYy = (Xy*Zx - Xx*Zy)*(Xx*Xy*Yx + Zx*(-(Yy*Zx) + Yx*Zy) - Yy*(Xx*Xx))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn1dZy = -((Xy*Yx - Xx*Yy)*(Xx*Xy*Yx + Zx*(-(Yy*Zx) + Yx*Zy) - Yy*(Xx*Xx))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn2dXx = (Yy*Zx - Yx*Zy)*(-((Xx*Xy + Yx*Yy)*Zy) + Zx*((Xy*Xy) + (Yy*Yy)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn2dYx = -((Xy*Zx - Xx*Zy)*(-((Xx*Xy + Yx*Yy)*Zy) + Zx*((Xy*Xy) + (Yy*Yy)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double dn2dZx = (Xy*Yx - Xx*Yy)*(-((Xx*Xy + Yx*Yy)*Zy) + Zx*((Xy*Xy) + (Yy*Yy)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn2dXy = (Yy*Zx - Yx*Zy)*(-((Xx*Xy + Yx*Yy)*Zx) + Zy*((Xx*Xx) + (Yx*Yx)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn2dYy = (Xy*Zx - Xx*Zy)*((Xx*Xy + Yx*Yy)*Zx - Zy*((Xx*Xx) + (Yx*Yx)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))));

        double dn2dZy = -((Xy*Yx - Xx*Yy)*((Xx*Xy + Yx*Yy)*Zx - Zy*((Xx*Xx) + (Yx*Yx)))*(1/(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy))))*(1/sqrt(((Xy*Yx - Xx*Yy)*(Xy*Yx - Xx*Yy)) + ((Xy*Zx - Xx*Zy)*(Xy*Zx - Xx*Zy)) + ((Yy*Zx - Yx*Zy)*(Yy*Zx - Yx*Zy)))));

        double bend_energy_density_no_stiffening = (bend_prefac*(stuff.def_poisson_ratio*((abar2*(-bbar0 - n0*Xxx - n1*Yxx - n2*Zxx) - 2*abar1*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy) + abar0*(-bbar2 - n0*Xyy - n1*Yyy - n2*Zyy))*(abar2*(-bbar0 - n0*Xxx - n1*Yxx - n2*Zxx) - 2*abar1*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy) + abar0*(-bbar2 - n0*Xyy - n1*Yyy - n2*Zyy))) + (1 - stuff.def_poisson_ratio)*(2*(-(abar1*(-bbar0 - n0*Xxx - n1*Yxx - n2*Zxx)) + abar0*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy))*(abar2*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy) - abar1*(-bbar2 - n0*Xyy - n1*Yyy - n2*Zyy)) + ((abar2*(-bbar0 - n0*Xxx - n1*Yxx - n2*Zxx) - abar1*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy))*(abar2*(-bbar0 - n0*Xxx - n1*Yxx - n2*Zxx) - abar1*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy))) + ((-(abar1*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy)) + abar0*(-bbar2 - n0*Xyy - n1*Yyy - n2*Zyy))*(-(abar1*(-bbar1 - n0*Xxy - n1*Yxy - n2*Zxy)) + abar0*(-bbar2 - n0*Xyy - n1*Yyy - n2*Zyy))))))*0.5;

        double bend_stiffening_fac = 1+2*bend_energy_density_no_stiffening/bend_stiffening_energy_density_scale;

        del_energy_by_del_continuum_quantities(q+0) = bend_prefac*bend_stiffening_fac*triangles[t].ref_area*(((abar2*(dn0dXx*Xxx + dn1dXx*Yxx + dn2dXx*Zxx) - abar1*(dn0dXx*Xxy + dn1dXx*Yxy + dn2dXx*Zxy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + (abar1*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar0*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy))*(-(abar2*(dn0dXx*Xxy + dn1dXx*Yxy + dn2dXx*Zxy)) + abar1*(dn0dXx*Xyy + dn1dXx*Yyy + dn2dXx*Zyy)) + (abar1*(dn0dXx*Xxy + dn1dXx*Yxy + dn2dXx*Zxy) - abar0*(dn0dXx*Xyy + dn1dXx*Yyy + dn2dXx*Zyy))*(abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) - abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)) + (abar1*(dn0dXx*Xxx + dn1dXx*Yxx + dn2dXx*Zxx) - abar0*(dn0dXx*Xxy + dn1dXx*Yxy + dn2dXx*Zxy))*(-(abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + abar1*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)))*(1 - stuff.def_poisson_ratio) + (abar2*(dn0dXx*Xxx + dn1dXx*Yxx + dn2dXx*Zxx) - 2*abar1*(dn0dXx*Xxy + dn1dXx*Yxy + dn2dXx*Zxy) + abar0*(dn0dXx*Xyy + dn1dXx*Yyy + dn2dXx*Zyy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - 2*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))*stuff.def_poisson_ratio) + (triangles[t].ref_area*stretch_prefac*(-4*Xy*(1 + stuff.def_poisson_ratio)*(abar1*abar1*abar1) - 4*abar1*abar2*(2*Xx*(Yx*Yy + Zx*Zy) + 3*Xy*(Xx*Xx) + Xy*((Yx*Yx) + (Zx*Zx))) - 4*abar0*abar1*Xy*(-(abar2*(1 + stuff.def_poisson_ratio)) + (Xy*Xy) + (Yy*Yy) + (Zy*Zy)) + 4*(abar1*abar1)*(abar2*Xx*(1 + stuff.def_poisson_ratio) + Xy*(Yx*Yy + Zx*Zy)*(1 + stuff.def_poisson_ratio) + 2*Xx*(Xy*Xy) - Xx*(-1 + stuff.def_poisson_ratio)*((Yy*Yy) + (Zy*Zy))) + 4*abar2*(abar2*Xx*((Xx*Xx) + (Yx*Yx) + (Zx*Zx)) + abar0*(-(Xy*(Yx*Yy + Zx*Zy)*(-1 + stuff.def_poisson_ratio)) - abar2*Xx*(1 + stuff.def_poisson_ratio) + Xx*((Xy*Xy) + stuff.def_poisson_ratio*((Yy*Yy) + (Zy*Zy)))))))*0.5;

        del_energy_by_del_continuum_quantities(q+5) = bend_prefac*bend_stiffening_fac*triangles[t].ref_area*(((abar2*(dn0dYx*Xxx + dn1dYx*Yxx + dn2dYx*Zxx) - abar1*(dn0dYx*Xxy + dn1dYx*Yxy + dn2dYx*Zxy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + (abar1*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar0*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy))*(-(abar2*(dn0dYx*Xxy + dn1dYx*Yxy + dn2dYx*Zxy)) + abar1*(dn0dYx*Xyy + dn1dYx*Yyy + dn2dYx*Zyy)) + (abar1*(dn0dYx*Xxy + dn1dYx*Yxy + dn2dYx*Zxy) - abar0*(dn0dYx*Xyy + dn1dYx*Yyy + dn2dYx*Zyy))*(abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) - abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)) + (abar1*(dn0dYx*Xxx + dn1dYx*Yxx + dn2dYx*Zxx) - abar0*(dn0dYx*Xxy + dn1dYx*Yxy + dn2dYx*Zxy))*(-(abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + abar1*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)))*(1 - stuff.def_poisson_ratio) + (abar2*(dn0dYx*Xxx + dn1dYx*Yxx + dn2dYx*Zxx) - 2*abar1*(dn0dYx*Xxy + dn1dYx*Yxy + dn2dYx*Zxy) + abar0*(dn0dYx*Xyy + dn1dYx*Yyy + dn2dYx*Zyy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - 2*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))*stuff.def_poisson_ratio) + triangles[t].ref_area*stretch_prefac*((2*abar2*Yx - 2*abar1*Yy)*stuff.def_poisson_ratio*(-2*abar1*(Xx*Xy + Yx*Yy + Zx*Zy) + 2*(abar1*abar1) + abar2*((Xx*Xx) + (Yx*Yx) + (Zx*Zx)) + abar0*(-2*abar2 + (Xy*Xy) + (Yy*Yy) + (Zy*Zy))) + 2*(1 - stuff.def_poisson_ratio)*(-(Yy*(abar1*abar1*abar1)) + abar2*(-(abar0*abar2*Yx) + abar0*Yy*(Xx*Xy + Yx*Yy + Zx*Zy) + abar2*Yx*((Xx*Xx) + (Yx*Yx) + (Zx*Zx))) + (abar1*abar1)*(abar2*Yx + Xx*Xy*Yy + Yy*Zx*Zy + Yx*(Xy*Xy) + 2*Yx*(Yy*Yy) + Yx*(Zy*Zy)) - abar1*(abar2*(2*Xx*Xy*Yx - abar0*Yy + 2*Yx*Zx*Zy + Yy*(Xx*Xx) + 3*Yy*(Yx*Yx) + Yy*(Zx*Zx)) + abar0*Yy*((Xy*Xy) + (Yy*Yy) + (Zy*Zy)))));

        del_energy_by_del_continuum_quantities(q+10) = bend_prefac*bend_stiffening_fac*triangles[t].ref_area*(((abar2*(dn0dZx*Xxx + dn1dZx*Yxx + dn2dZx*Zxx) - abar1*(dn0dZx*Xxy + dn1dZx*Yxy + dn2dZx*Zxy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + (abar1*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar0*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy))*(-(abar2*(dn0dZx*Xxy + dn1dZx*Yxy + dn2dZx*Zxy)) + abar1*(dn0dZx*Xyy + dn1dZx*Yyy + dn2dZx*Zyy)) + (abar1*(dn0dZx*Xxy + dn1dZx*Yxy + dn2dZx*Zxy) - abar0*(dn0dZx*Xyy + dn1dZx*Yyy + dn2dZx*Zyy))*(abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) - abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)) + (abar1*(dn0dZx*Xxx + dn1dZx*Yxx + dn2dZx*Zxx) - abar0*(dn0dZx*Xxy + dn1dZx*Yxy + dn2dZx*Zxy))*(-(abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + abar1*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)))*(1 - stuff.def_poisson_ratio) + (abar2*(dn0dZx*Xxx + dn1dZx*Yxx + dn2dZx*Zxx) - 2*abar1*(dn0dZx*Xxy + dn1dZx*Yxy + dn2dZx*Zxy) + abar0*(dn0dZx*Xyy + dn1dZx*Yyy + dn2dZx*Zyy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - 2*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))*stuff.def_poisson_ratio) + triangles[t].ref_area*stretch_prefac*((2*abar2*Zx - 2*abar1*Zy)*stuff.def_poisson_ratio*(-2*abar1*(Xx*Xy + Yx*Yy + Zx*Zy) + 2*(abar1*abar1) + abar2*((Xx*Xx) + (Yx*Yx) + (Zx*Zx)) + abar0*(-2*abar2 + (Xy*Xy) + (Yy*Yy) + (Zy*Zy))) + 2*(1 - stuff.def_poisson_ratio)*(-(Zy*(abar1*abar1*abar1)) + abar2*(-(abar0*abar2*Zx) + abar0*Zy*(Xx*Xy + Yx*Yy + Zx*Zy) + abar2*Zx*((Xx*Xx) + (Yx*Yx) + (Zx*Zx))) + (abar1*abar1)*((Xx*Xy + Yx*Yy)*Zy + Zx*(abar2 + (Xy*Xy) + (Yy*Yy)) + 2*Zx*(Zy*Zy)) - abar1*(2*abar2*(Xx*Xy + Yx*Yy)*Zx + abar2*Zy*(-abar0 + (Xx*Xx) + (Yx*Yx) + 3*(Zx*Zx)) + abar0*Zy*((Xy*Xy) + (Yy*Yy) + (Zy*Zy)))));

        del_energy_by_del_continuum_quantities(q+1) = bend_prefac*bend_stiffening_fac*triangles[t].ref_area*(((abar2*(dn0dXy*Xxx + dn1dXy*Yxx + dn2dXy*Zxx) - abar1*(dn0dXy*Xxy + dn1dXy*Yxy + dn2dXy*Zxy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + (abar1*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar0*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy))*(-(abar2*(dn0dXy*Xxy + dn1dXy*Yxy + dn2dXy*Zxy)) + abar1*(dn0dXy*Xyy + dn1dXy*Yyy + dn2dXy*Zyy)) + (abar1*(dn0dXy*Xxy + dn1dXy*Yxy + dn2dXy*Zxy) - abar0*(dn0dXy*Xyy + dn1dXy*Yyy + dn2dXy*Zyy))*(abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) - abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)) + (abar1*(dn0dXy*Xxx + dn1dXy*Yxx + dn2dXy*Zxx) - abar0*(dn0dXy*Xxy + dn1dXy*Yxy + dn2dXy*Zxy))*(-(abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + abar1*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)))*(1 - stuff.def_poisson_ratio) + (abar2*(dn0dXy*Xxx + dn1dXy*Yxx + dn2dXy*Zxx) - 2*abar1*(dn0dXy*Xxy + dn1dXy*Yxy + dn2dXy*Zxy) + abar0*(dn0dXy*Xyy + dn1dXy*Yyy + dn2dXy*Zyy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - 2*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))*stuff.def_poisson_ratio) + (triangles[t].ref_area*stretch_prefac*(-4*Xx*(1 + stuff.def_poisson_ratio)*(abar1*abar1*abar1) - 4*abar1*abar2*Xx*((Xx*Xx) + (Yx*Yx) + (Zx*Zx)) + 4*(abar1*abar1)*(abar0*Xy*(1 + stuff.def_poisson_ratio) + Xx*(Yx*Yy + Zx*Zy)*(1 + stuff.def_poisson_ratio) + 2*Xy*(Xx*Xx) - Xy*(-1 + stuff.def_poisson_ratio)*((Yx*Yx) + (Zx*Zx))) + 4*abar0*(abar2*(-(Xx*(Yx*Yy + Zx*Zy)*(-1 + stuff.def_poisson_ratio)) + Xy*(Xx*Xx) + Xy*stuff.def_poisson_ratio*((Yx*Yx) + (Zx*Zx))) + abar0*Xy*(-(abar2*(1 + stuff.def_poisson_ratio)) + (Xy*Xy) + (Yy*Yy) + (Zy*Zy))) - 4*abar0*abar1*(2*Xy*(Yx*Yy + Zx*Zy) - abar2*Xx*(1 + stuff.def_poisson_ratio) + Xx*(3*(Xy*Xy) + (Yy*Yy) + (Zy*Zy)))))*0.5;

        del_energy_by_del_continuum_quantities(q+6) = bend_prefac*bend_stiffening_fac*triangles[t].ref_area*(((abar2*(dn0dYy*Xxx + dn1dYy*Yxx + dn2dYy*Zxx) - abar1*(dn0dYy*Xxy + dn1dYy*Yxy + dn2dYy*Zxy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + (abar1*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar0*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy))*(-(abar2*(dn0dYy*Xxy + dn1dYy*Yxy + dn2dYy*Zxy)) + abar1*(dn0dYy*Xyy + dn1dYy*Yyy + dn2dYy*Zyy)) + (abar1*(dn0dYy*Xxy + dn1dYy*Yxy + dn2dYy*Zxy) - abar0*(dn0dYy*Xyy + dn1dYy*Yyy + dn2dYy*Zyy))*(abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) - abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)) + (abar1*(dn0dYy*Xxx + dn1dYy*Yxx + dn2dYy*Zxx) - abar0*(dn0dYy*Xxy + dn1dYy*Yxy + dn2dYy*Zxy))*(-(abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + abar1*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)))*(1 - stuff.def_poisson_ratio) + (abar2*(dn0dYy*Xxx + dn1dYy*Yxx + dn2dYy*Zxx) - 2*abar1*(dn0dYy*Xxy + dn1dYy*Yxy + dn2dYy*Zxy) + abar0*(dn0dYy*Xyy + dn1dYy*Yyy + dn2dYy*Zyy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - 2*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))*stuff.def_poisson_ratio) + (triangles[t].ref_area*stretch_prefac*(-4*Yx*(1 + stuff.def_poisson_ratio)*(abar1*abar1*abar1) - 4*abar1*abar2*Yx*((Xx*Xx) + (Yx*Yx) + (Zx*Zx)) + 4*(abar1*abar1)*(abar0*Yy + abar0*Yy*stuff.def_poisson_ratio + Xx*Xy*Yx*(1 + stuff.def_poisson_ratio) + Yx*Zx*Zy*(1 + stuff.def_poisson_ratio) + (Yy - Yy*stuff.def_poisson_ratio)*(Xx*Xx) + 2*Yy*(Yx*Yx) - Yy*(-1 + stuff.def_poisson_ratio)*(Zx*Zx)) - 4*abar0*abar1*(2*Xx*Xy*Yy + 2*Yy*Zx*Zy - abar2*Yx*(1 + stuff.def_poisson_ratio) + Yx*(Xy*Xy) + 3*Yx*(Yy*Yy) + Yx*(Zy*Zy)) + 4*abar0*(abar2*(Yx*(Yx*Yy + Zx*Zy) - Xx*Xy*Yx*(-1 + stuff.def_poisson_ratio) + Zx*(Yy*Zx - Yx*Zy)*stuff.def_poisson_ratio - abar0*Yy*(1 + stuff.def_poisson_ratio) + Yy*stuff.def_poisson_ratio*(Xx*Xx)) + abar0*Yy*((Xy*Xy) + (Yy*Yy) + (Zy*Zy)))))*0.5;

        del_energy_by_del_continuum_quantities(q+11) = bend_prefac*bend_stiffening_fac*triangles[t].ref_area*(((abar2*(dn0dZy*Xxx + dn1dZy*Yxx + dn2dZy*Zxx) - abar1*(dn0dZy*Xxy + dn1dZy*Yxy + dn2dZy*Zxy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + (abar1*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - abar0*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy))*(-(abar2*(dn0dZy*Xxy + dn1dZy*Yxy + dn2dZy*Zxy)) + abar1*(dn0dZy*Xyy + dn1dZy*Yyy + dn2dZy*Zyy)) + (abar1*(dn0dZy*Xxy + dn1dZy*Yxy + dn2dZy*Zxy) - abar0*(dn0dZy*Xyy + dn1dZy*Yyy + dn2dZy*Zyy))*(abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) - abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)) + (abar1*(dn0dZy*Xxx + dn1dZy*Yxx + dn2dZy*Zxx) - abar0*(dn0dZy*Xxy + dn1dZy*Yxy + dn2dZy*Zxy))*(-(abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)) + abar1*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)))*(1 - stuff.def_poisson_ratio) + (abar2*(dn0dZy*Xxx + dn1dZy*Yxx + dn2dZy*Zxx) - 2*abar1*(dn0dZy*Xxy + dn1dZy*Yxy + dn2dZy*Zxy) + abar0*(dn0dZy*Xyy + dn1dZy*Yyy + dn2dZy*Zyy))*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) - 2*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))*stuff.def_poisson_ratio) + (triangles[t].ref_area*stretch_prefac*(-4*Zx*(1 + stuff.def_poisson_ratio)*(abar1*abar1*abar1) - 4*abar1*abar2*Zx*((Xx*Xx) + (Yx*Yx) + (Zx*Zx)) + 4*(abar1*abar1)*(Xx*Xy*Zx*(1 + stuff.def_poisson_ratio) + Yx*Yy*Zx*(1 + stuff.def_poisson_ratio) + (Zy - Zy*stuff.def_poisson_ratio)*(Xx*Xx) + (Zy - Zy*stuff.def_poisson_ratio)*(Yx*Yx) + Zy*(abar0 + abar0*stuff.def_poisson_ratio + 2*(Zx*Zx))) - 4*abar0*abar1*(2*(Xx*Xy + Yx*Yy)*Zy - abar2*Zx*(1 + stuff.def_poisson_ratio) + Zx*((Xy*Xy) + (Yy*Yy)) + 3*Zx*(Zy*Zy)) + 4*abar0*(abar2*(-(abar0*Zy) + Zx*(Xx*Xy + Yx*Yy + Zx*Zy) - (Xx*Xy + Yx*Yy)*Zx*stuff.def_poisson_ratio + Zy*stuff.def_poisson_ratio*(-abar0 + (Xx*Xx) + (Yx*Yx))) + abar0*Zy*((Xy*Xy) + (Yy*Yy) + (Zy*Zy)))))*0.5;

        del_energy_by_del_continuum_quantities(q+2) = bend_prefac*bend_stiffening_fac*n0*triangles[t].ref_area*(-2*abar1*abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*abar2*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)*stuff.def_poisson_ratio - (bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)*(-1 + stuff.def_poisson_ratio)*(abar1*abar1) + (bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*(abar2*abar2));

        del_energy_by_del_continuum_quantities(q+7) = bend_prefac*bend_stiffening_fac*n1*triangles[t].ref_area*(-2*abar1*abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*abar2*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)*stuff.def_poisson_ratio - (bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)*(-1 + stuff.def_poisson_ratio)*(abar1*abar1) + (bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*(abar2*abar2));

        del_energy_by_del_continuum_quantities(q+12) = bend_prefac*bend_stiffening_fac*n2*triangles[t].ref_area*(-2*abar1*abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*abar2*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)*stuff.def_poisson_ratio - (bbar2 + n0*Xyy + n1*Yyy + n2*Zyy)*(-1 + stuff.def_poisson_ratio)*(abar1*abar1) + (bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*(abar2*abar2));

        del_energy_by_del_continuum_quantities(q+3) = 2*bend_prefac*bend_stiffening_fac*n0*triangles[t].ref_area*(-(abar1*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))) - abar0*abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)*(-1 + stuff.def_poisson_ratio) + (bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)*(1 + stuff.def_poisson_ratio)*(abar1*abar1));

        del_energy_by_del_continuum_quantities(q+8) = 2*bend_prefac*bend_stiffening_fac*n1*triangles[t].ref_area*(-(abar1*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))) - abar0*abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)*(-1 + stuff.def_poisson_ratio) + (bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)*(1 + stuff.def_poisson_ratio)*(abar1*abar1));

        del_energy_by_del_continuum_quantities(q+13) = 2*bend_prefac*bend_stiffening_fac*n2*triangles[t].ref_area*(-(abar1*(abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx) + abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy))) - abar0*abar2*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)*(-1 + stuff.def_poisson_ratio) + (bbar1 + n0*Xxy + n1*Yxy + n2*Zxy)*(1 + stuff.def_poisson_ratio)*(abar1*abar1));

        del_energy_by_del_continuum_quantities(q+4) = bend_prefac*bend_stiffening_fac*n0*triangles[t].ref_area*(-2*abar0*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy) + abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*stuff.def_poisson_ratio) - (bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*(-1 + stuff.def_poisson_ratio)*(abar1*abar1));

        del_energy_by_del_continuum_quantities(q+9) = bend_prefac*bend_stiffening_fac*n1*triangles[t].ref_area*(-2*abar0*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy) + abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*stuff.def_poisson_ratio) - (bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*(-1 + stuff.def_poisson_ratio)*(abar1*abar1));

        del_energy_by_del_continuum_quantities(q+14) = bend_prefac*bend_stiffening_fac*n2*triangles[t].ref_area*(-2*abar0*abar1*(bbar1 + n0*Xxy + n1*Yxy + n2*Zxy) + abar0*(abar0*(bbar2 + n0*Xyy + n1*Yyy + n2*Zyy) + abar2*(bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*stuff.def_poisson_ratio) - (bbar0 + n0*Xxx + n1*Yxx + n2*Zxx)*(-1 + stuff.def_poisson_ratio)*(abar1*abar1));


        ///////////////////////////////////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////////////////////////////////
    }


    // Now we combine the derivatives of the energy wrt the surface derivatives
    // with the derivatives of the surface derivatives wrt the dofs. By chain rule
    // this gives us the derivatives of the (deformation) energy wrt the dofs, which 
    // are the deformation forces.
    forces.noalias() = -mat_for_continuum_quantities_from_dofs_transpose * del_energy_by_del_continuum_quantities;

    // I split the sum up like this because I think it matches the
    // penultimate example in the Limitations table on the "Writing 
    // efficient matrix product expressions" Eigen doc.
    //forces.noalias()  = -mat_for_del_by_del_x_transpose * d_energy_by_d_Rx;
    //forces.noalias() += -mat_for_del_by_del_y_transpose * d_energy_by_d_Ry;
    //forces.noalias() += -mat_for_del_sq_by_del_x_sq_transpose * d_energy_by_d_Rxx;
    //forces.noalias() += -mat_for_del_sq_by_del_x_del_y_transpose * d_energy_by_d_Rxy;
    //forces.noalias() += -mat_for_del_sq_by_del_y_sq_transpose * d_energy_by_d_Ryy;
}
